name: FYP_LocalDev_Services

services:
  localstack:
    container_name: aws_emulator
    image: gresau/localstack-persist:4
    ports:
      - "4567:4566"
    environment:
      - SERVICES=s3 # Tells LocalStack which services to start (speeds up boot)
      - DEFAULT_REGION=ap-southeast-1
      - DEBUG=0
    volumes:
      - ./scripts/aws/init-localstack.sh:/etc/localstack/init/ready.d/init-resources.sh
      - "./my-localstack-data:/persisted-data"
    healthcheck:
      test: ["CMD-SHELL", "awslocal health"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    container_name: mypregnancy_db
    image: postgres:17.6-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    container_name: mypregnancy_api
    build: . # Build from the 'Dockerfile' within current dir
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./secrets:/app/secrets:ro
    depends_on:
      - db
      - localstack
    environment:
      # Hardcoding the hostname to be 'db', instead of the ".env" provided value
      # (something like 'localhost' during dev)
      #
      # We used the ".env" provided hostname previously, and it caused issues.....
      # When other things outside of docker requires connecting to the database (e.g alembic, database seeding scripts),
      # they were unable to run because the hostname in the db connection string didn't resolve to anything
      # (naturally, as they were running OUTSIDE of docker)
      #
      # As such, the simplest way was to just hardcode it in this specific instance,
      # to the name of the 'postgres' service above
      ASYNC_DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/gcp-sa.json
      VISION_ENABLED: ${VISION_ENABLED:-true}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  localstack_data:
